In [1]:
'''
Machine Learning - 
    Computers ability to learn without explicitely programmed
    i/p - Algorithm - O/p
    Choose i/p, choose algorithms - i/p relvent to algorithm 
    different column - different results
    
Algorithms
    supervised learning 
        - i/p, o/p both are provided to algorithm
        - gmail - spam or not
            from, to address
            subject line
            spelling Error
            Number of links
        
    unsupervised learning 
        - no o/p
        - classify i/p
    
'''

'\nMachine Learning - \n    Computers ability to learn without explicitely programmed\n    i/p - Algorithm - O/p\n    Choose i/p, choose algorithms - i/p relvent to algorithm \n    different column - different results\n    \nAlgorithms\n    supervised learning \n        - i/p, o/p both are provided to algorithm\n        - gmail - spam or not\n            from, to address\n            subject line\n            spelling Error\n            Number of links\n        \n    unsupervised learning \n        - no o/p\n        - classify i/p\n    \n'

In [2]:
'''
scikit package 
    - helps in clean input and provide to algorithm
    - statistical module helps in design models
'''

'\nscikit package \n    - helps in clean input and provide to algorithm\n    - statistical module helps in design models\n'

In [3]:
'''
Types of machine learning algorithms
    Classification
    Regression
    clustering
    dimentionality reduction
'''

'\nTypes of machine learning algorithms\n    Classification\n    Regression\n    clustering\n    dimentionality reduction\n'

In [4]:
'''
    Problem - Predict Profits Per Sale
    
    i/p - features - X
        sales
    o/p - y
        profits
        
    Sales | Profit    
    30    |   3
    40    |   4
    50    |   5
    60    |   6
    
    0.1X = y  : fit a model
    
    100   |   10      
    
'''

'\n    Problem - Predict Profits Per Sale\n    \n    i/p - features - X\n        sales\n    o/p - y\n        profits\n        \n    Sales | Profit    \n    30    |   3\n    40    |   4\n    50    |   5\n    60    |   6\n    \n    0.1X = y  : fit a model\n    \n    100   |   10      \n    \n'

In [5]:
'''
    Observations: rows
    Featured: X
    Target: y
'''

'\n    Observations: rows\n    Featured: X\n    Target: y\n'

In [6]:
'''
Supervised
    - Linear Regression
    - Logistic Reression
    - Classification
    - Decision Tree
    - KNN
    - Naive Bayes
    
Unsupervised
    - Centroid Based 
    - Connectivity Based
    - Density Based
    - Probablistic
'''

'\nSupervised\n    - Linear Regression\n    - Logistic Reression\n    - Classification\n    - Decision Tree\n    - KNN\n    - Naive Bayes\n    \nUnsupervised\n    - Centroid Based \n    - Connectivity Based\n    - Density Based\n    - Probablistic\n'

# Import Data Set

Download data from URL

In [7]:
#from IPython.display import HTML
#HTML('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

import pandas as pd

data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

print(data)


     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa


In [8]:
type(data)

pandas.core.frame.DataFrame

Inbuilt iris dataset from Sci Kit

In [9]:
from sklearn.datasets import load_iris
iris = load_iris()

In [10]:
type(iris)
#bunch is special datatype - many attributes

sklearn.utils.Bunch

In [11]:
print(iris.feature_names) #feature

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print(iris.target_names) #target

['setosa' 'versicolor' 'virginica']


# Data Pre-Processing

Both target and data should be numerical

In [13]:
print(iris.target) #y: vector format

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
print(iris.data) #X: matrix format 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Both target and data should be numpy array

In [15]:
print(type(iris.data)) #X

<class 'numpy.ndarray'>


In [16]:
print(type(iris.target)) #y

<class 'numpy.ndarray'>


In [17]:
X=iris.data
y=iris.target

# Fitting a machine learning model

In [18]:
'''
Fit Model :
    1. import the class
    2. instantiate
    3. fit the model
'''

'\nFit Model :\n    1. import the class\n    2. instantiate\n    3. fit the model\n'

# KNN

In [19]:
'''
KNN : 
    plot (x,y,color) 
    - mark territory for color 
    - territory predict the new point
    - http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
'''

'\nKNN : \n    plot (x,y,color) \n    - mark territory for color \n    - territory predict the new point\n    - http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html\n'

KNN = 1 

In [20]:
# import package
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=1)
print(knn1)

KNeighborsClassifier(n_neighbors=1)


In [21]:
# fit model
knn1.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [22]:
#predict output
prediction = knn1.predict([[2,4,3,1]])
print(prediction)

[0]


In [23]:
type(prediction)

numpy.ndarray

In [24]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [25]:
print(iris.target_names[0])

setosa


In [26]:
prediction = knn1.predict([[2,4,3,1],[4,6,5,3]])
print(prediction)

[0 2]


KNN = 5

In [27]:
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X,y)

KNeighborsClassifier()

In [28]:
prediction5 = knn5.predict([[2,4,3,1],[4,6,5,3]])
print(prediction5)

[0 1]


KNN from 1 to 30

In [29]:
for i in range(1,31):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X,y)
    prediction = knn.predict([[2,4,3,1],[4,6,5,3]])
    print('knn'+str(i)+' '+str(prediction))

knn1 [0 2]
knn2 [0 2]
knn3 [0 2]
knn4 [0 1]
knn5 [0 1]
knn6 [0 1]
knn7 [0 2]
knn8 [0 2]
knn9 [0 2]
knn10 [0 2]
knn11 [0 2]
knn12 [0 2]
knn13 [0 2]
knn14 [0 2]
knn15 [0 2]
knn16 [0 2]
knn17 [0 2]
knn18 [0 2]
knn19 [0 2]
knn20 [0 2]
knn21 [0 2]
knn22 [0 2]
knn23 [0 2]
knn24 [0 2]
knn25 [0 2]
knn26 [0 2]
knn27 [0 2]
knn28 [0 2]
knn29 [0 2]
knn30 [0 2]


# Logistic Regression - Classification

In [30]:
#import package for Logistic Regression
from sklearn.linear_model import LogisticRegression
logisticreg = LogisticRegression()

In [31]:
#fir a model
logisticreg.fit(X,y)

C:\Users\LocalAdmin\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [57]:
logisticreg = LogisticRegression(max_iter=200) #default 100
logisticreg.fit(X,y)

LogisticRegression(max_iter=200)

In [58]:
predict_lr = logisticreg.predict([[2,4,3,1],[4,6,5,3]])
print(predict_lr)

[0 2]


In [33]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


Predicting with the available answer

In [59]:
prediction = knn.predict([[5.1,3.5,1.4,0.2],[6.3,3.3,4.7,1.6]])
print(prediction)

prediction5 = knn5.predict([[5.1,3.5,1.4,0.2],[6.3,3.3,4.7,1.6]])
print(prediction5)

prediction_lr = logisticreg.predict(([[5.1,3.5,1.4,0.2],[6.3,3.3,4.7,1.6]]))
print(prediction_lr)

[0 1]
[0 1]
[0 1]


# Validation using model selection  (Train - Test)

In [76]:
# import packages for train test split

import numpy as np
from sklearn.model_selection import train_test_split

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [78]:
print(X.shape) #150 rows 4 column

(150, 4)


In [79]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [80]:
print(y_train.shape)
print(y_test.shape)

(105,)
(45,)


In [81]:
#Logistic regression with train dataset
from sklearn.linear_model import LogisticRegression
logisticreg = LogisticRegression()
logisticreg.fit(X_train, y_train)

C:\Users\LocalAdmin\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [82]:
#predictions calculated
y_pred = logisticreg.predict(X_test)

In [83]:
#accuracy_score
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.9777777777777777


In [84]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=1)

knn1.fit(X_train,y_train)
y_pred = knn1.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9555555555555556


In [85]:
from sklearn.neighbors import KNeighborsClassifier
knn5 = KNeighborsClassifier(n_neighbors=5)

knn5.fit(X_train,y_train)
y_pred = knn5.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9777777777777777


In [86]:
from sklearn.neighbors import KNeighborsClassifier
knn8 = KNeighborsClassifier(n_neighbors=8)

knn8.fit(X_train,y_train)
y_pred = knn8.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9555555555555556


Train - Test 40%

In [87]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [88]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(150, 4)
(90, 4)
(60, 4)


In [89]:
from sklearn.linear_model import LogisticRegression
logisticreg = LogisticRegression()
logisticreg.fit(X_train, y_train)

LogisticRegression()

In [90]:
y_pred = logisticreg.predict(X_test)

from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.9666666666666667


In [91]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=1)

knn1.fit(X_train,y_train)
y_pred = knn1.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.95


In [92]:
from sklearn.neighbors import KNeighborsClassifier
knn5 = KNeighborsClassifier(n_neighbors=5)

knn5.fit(X_train,y_train)
y_pred = knn5.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9666666666666667


In [93]:
from sklearn.neighbors import KNeighborsClassifier
knn8 = KNeighborsClassifier(n_neighbors=8)

knn8.fit(X_train,y_train)
y_pred = knn8.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.9833333333333333


KNN range from 1 to 30

In [100]:
knn_scores=[]

for i in range(1,31):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    knn_scores.append(metrics.accuracy_score(y_test,y_pred))
    #knn_scores[i]=metrics.accuracy_score(y_test,y_pred)
    
print(knn_scores)

[0.95, 0.95, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9833333333333333, 0.9666666666666667, 0.9833333333333333, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.9666666666666667, 0.95, 0.95, 0.95, 0.95, 0.9666666666666667, 0.95, 0.9666666666666667]


Draw plot

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(range(1,31),knn_scores)

plt.xlabel('Accuracy_score')
plt.ylabel('n_neighbors')

In [ ]:
#k-fold - cross validation - choose test 0-5, 6-10, ... rest training - mean of accuracy score

In [ ]:
from sklearn.model_selection import cross_val_score
knn5 = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(knn, X, y, cv=10, scoring ='accuracy')
print(scores)
print(scores.mean())

In [ ]:
from sklearn.model_selection import cross_val_score
knn5 = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(knn, X, y, cv=5, scoring ='accuracy')
print(scores)
print(scores.mean())

In [ ]:
k_scores=[]
for i in range(1,45):
    knn=KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(knn, X, y, cv=5, scoring ='accuracy')
    k_scores.append(scores.mean())
    
print(k_scores)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(range(1,45),k_scores)

plt.xlabel('k value for KNN algo')
plt.ylabel('mean accuracy value')